// Caterwaul vector geometry | Spencer Tipping
// Licensed under the terms of the MIT source code license

// Introduction.
// A basic vector library optimized for the 3D case. Vectors are generally immutable. You're free to change them, but they may be aliased in ways that make that dangerous.

  caterwaul.tconfiguration('std', 'vector', function () {
    this.vector = fc[x, y, z][this.x = x, this.y = y, this.z = z] /se[_.prototype /se[
      _.plus(v, x) = let[x = x || 1] in new this.constructor(this.x + v.x * x, this.y + v.y * x, this.z + v.z * x),
      _.dot(v)     = this.x * v.x + this.y * v.y + this.z * v.z,
      _.cross(v)   = new _.constructor(this.y * v.z - this.z * v.y, this.z * v.x - this.x * v.z, this.x * v.y - this.y * v.x),
      _.times(x)   = x instanceof this.constructor ? new this.constructor(this.x * x.x, this.y * x.y, this.z * x.z) : new this.constructor(this.x * x, this.y * x, this.z * x),

      _.toString() = '<#{this.x}, #{this.y}, #{this.z}>',

      _.unit(x)    = this.times((x || 1.0) / Math.sqrt(this.dot(this))),
      _.proj(v)    = v.times(this.dot(v) / v.dot(v)),
      _.orth(v)    = this.plus(this.proj(v), -1)]]});

// Generated by SDoc 
